# Generated by Django 6.0.1 on 2026-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('carColour', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
