# Generated by Django 6.0.1 on 2026-02-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internName', models.CharField(max_length=100)),
                ('internAge', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'intern',
            },
        ),
        migrations.CreateModel(
            name='internDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internPhone', models.CharField(max_length=10)),
                ('internGender', models.CharField(max_length=10)),
                ('internID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.intern')),
            ],
            options={
                'db_table': 'internDetails',
            },
        ),
    ]
