# Generated by Django 6.0.1 on 2026-02-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoName', models.CharField(max_length=100)),
                ('CoAdress', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('CoPhone', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmID', models.IntegerField(max_length=25)),
                ('EmName', models.CharField(max_length=100)),
                ('EmSalary', models.IntegerField(max_length=50)),
                ('ComName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.company')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
