# Generated by Django 6.0.1 on 2026-02-08 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=200)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.project')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.module')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_spent', models.FloatField()),
                ('log_date', models.DateField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.task')),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='test1.user')),
            ],
            options={
                'db_table': 'time_logs',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user'),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('reported_date', models.DateField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.task')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to='test1.user')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='test1.user')),
            ],
            options={
                'db_table': 'bugs',
            },
        ),
    ]
